### ISSUE TITLE
unable to configure the device

### ISSUE THREAD

**Issue by pickeld** [hllhll/HomeAssistant-ekon-local#11]
Hey, 
HA was unable to migrate the device.

> 2020-12-20 11:29:45 INFO (MainThread) [custom_components.ekon-local.climate] Setting up Ekon-local climate platform
>2020-12-20 11:29:45 INFO (MainThread) [custom_components.ekon-local.climate] Creating Ekon-local climate controller
>2020-12-20 11:29:45 INFO (MainThread) [custom_components.ekon-local.climate] HAEkonLocalClimateController - Creating UDP Server
>2020-12-20 11:29:45 DEBUG (MainThread) [custom_components.ekon-local.climate] Starting Ekon-local server
>2020-12-20 11:29:45 INFO (MainThread) [custom_components.ekon-local.climate] Starting UDP Server on port 6343
>2020-12-20 11:29:45 INFO (MainThread) [custom_components.ekon-local.climate] UDP Server started
>2020-12-20 11:29:45 INFO (MainThread) [custom_components.ekon-local.climate] Migrating Ekon device
>2020-12-20 11:29:45 ERROR (SyncWorker_2) [custom_components.ekon-local.climate] **Error in migration [Errno 111] Connection refused**
>2020-12-20 11:29:46 ERROR (MainThread) [custom_components.ekon-local.climate] **Error migrating device 192.168.x.x**
>2020-12-20 11:29:46 INFO (MainThread) [custom_components.ekon-local.climate] Finished setting up Ekon-local climate platform

when trying to configure the device manualy using:

`from pyekonlib.Migration import SetDeviceUDPServer

SetDeviceUDPServer("192.168.x.x", "192.168.x.x", 6343)`

i get 

> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by hllhll** [comment]
Hi, Make sure the ekon device is at the _said_ address.
Are you this is it's address?
Can you access port 80 directly with any other client? (Port 80 should be opened)

**Comment by pickeld** [comment]
unable to connect over port 80, 
![image](https://user-images.githubusercontent.com/13360982/102710225-8dc7da00-42b9-11eb-861b-096135faa994.png)

**Comment by hllhll** [comment]
Is it possible you have the wrong IP Address?

**Comment by pickeld** [comment]
![image](https://user-images.githubusercontent.com/13360982/102710296-10e93000-42ba-11eb-8eee-3ac462969028.png)
 Nope. :/

**Comment by hllhll** [comment]
See this is how the original app does this, it detects ip address in 1 of 2 ways:
1. Using Esp-Smart-Config to detect and make the device join the network, it's ip address is fetched as a result from the Espressif library. Or, alternetivly
2. Sends a broadcast messages to the local network to [discover devices](https://github.com/hllhll/pyekonlib/issues/4)

**Comment by hllhll** [comment]
Hostname published by the device should be `EKON` 
![image](https://user-images.githubusercontent.com/2906606/102710362-6b828c00-42ba-11eb-8c6e-570899f4298d.png)

**Comment by pickeld** [comment]
i can see the broadcast
![image](https://user-images.githubusercontent.com/13360982/102710397-9cfb5780-42ba-11eb-82c2-a9e68bea1ddc.png)

**Comment by hllhll** [comment]
I'm still not convinced this is the device you're looking for,
Can you show what's the data in the packets? Does it looks like the "question"? like the response? [here](https://github.com/hllhll/pyekonlib/issues/4)

**Comment by pickeld** [comment]
![image](https://user-images.githubusercontent.com/13360982/102710513-91f4f700-42bb-11eb-82b0-10feec14bfe3.png)

i just got it installed today, maybe its a new version?
im using the app Tadiran IOT
seems like the device version is 1.1.1

**Comment by hllhll** [comment]
Sorry, this project is **not** for Tadiran IoT - Which is Tuya-Smart-based... it's for their older "Tadiran connect"...

**Comment by pickeld** [comment]
aw, how embarrassing. 
sorry!

**Comment by hllhll** [comment]
It would be very interesting to see if this can be done to it too, I'll be glad to help where possible.
Tuya-enabled integration and app should work Out-of-the-box

**Comment by pickeld** [comment]
thanks, you mean they should be auto discovered? apparently its doesn't

**Comment by hllhll** [comment]
I'm not much familiarize with Tuya-based products,
Tuya is a generic framework+library+cloud services for smart devices, you can look up online how to connect with tuya enabled devices (or more specificall, HVACs). You can also try asking in one of the facebook groups :)
