### ISSUE TITLE
No 'version' key in manifest file, see log line

### ISSUE THREAD

**Issue by shlomki** [hllhll/HomeAssistant-ekon-local#12]
As of HomeAssistant 2021.4, the manifest file has to include a 'version' key. 

See log line:
[homeassistant.loader] No 'version' key in the manifest file for custom integration 'ekon-local'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ekon-local'

**Comment by leranp** [comment]
This is the PR for adding the version number: #13

**Comment by hllhll** [comment]
Resolved in https://github.com/hllhll/HomeAssistant-ekon-local/pull/13 ?
(Thanks @leranp )
