### ISSUE TITLE
Missing version key

### ISSUE THREAD

**Issue by LiorTobias** [hllhll/HomeAssistant-ekon-local#14]
Saw this error in the log:

Logger: homeassistant.loader
Source: loader.py:794
First occurred: 12:17:15 PM (1 occurrences)
Last logged: 12:17:15 PM

No 'version' key in the manifest file for custom integration 'ekon-local'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ekon-local'

Appreciate your help, thank you

**Comment by hllhll** [comment]
Duplicate of https://github.com/hllhll/HomeAssistant-ekon-local/issues/12
Was fixed by a recent PR
