### ISSUE TITLE
Need help with local Ekon 

### ISSUE THREAD

**Issue by drorya1** [hllhll/HomeAssistant-ekon-local#15]
Hi Hillel
I have installed the local ekon
configured both IP oif HA and IP of the AC yet the component does not work 
Attaching the log 
I saw that Mii is problematic as well (-:
[Home_Assistant_Log_May24th21.txt](https://github.com/hllhll/HomeAssistant-EKON-iAircon/files/6532862/Home_Assistant_Log_May24th21.txt)

**Comment by hllhll** [comment]
It looks like you set up the files inside `custom_components/climate_local` instead of `custom_components/ekon-local`

**Comment by drorya1** [comment]
[home-assistant.log](https://github.com/hllhll/HomeAssistant-ekon-local/files/6546505/home-assistant.log)
Changed the name of the directory and rebooted the VM 
![image](https://user-images.githubusercontent.com/79847067/119656662-9b1e5d00-be33-11eb-9e7e-4191634bffd4.png)

**Comment by drorya1** [comment]
[home-assistant.log](https://github.com/hllhll/HomeAssistant-ekon-local/files/6547061/home-assistant.log)

**Comment by yuvalmesika** [comment]
based on your logs you still referring to the regular ekon custom component
2021-05-26 16:32:36 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform ekon
you need to reconfigure your climate entity
climate: 
- platform: ekon-local
  name: MyHVAC                   # Please, no spaces
  udp_server_port: 6343          # Can be anything, make sure it's accessible
  udp_server_addr: 192.168.1.10  # Optional, HA ip address
  device_addr: 192.168.1.25      # Optional, for auto-configuring the device

**Comment by hllhll** [comment]
I talked to @drorya1  seems that everything is good now :)
