### ISSUE TITLE
Cant Configure 2 airconet devices

### ISSUE THREAD

**Issue by cruzaderplyr** [hllhll/HomeAssistant-ekon-local#18]
sorry about my english, im triying to configure 2 airconet devices (both of them are on my same network, one is the AC from the living room and the other is the AC from my bedroom) but im having problems setting the code for both of them. indivitually works fine but when i put the 2 codes on the configyaml, one connects, and the other not, and both of them stop working. i have to mannually reset and reconfigure both, and disable the code. if you can help me pleassee....and again, sorry for my english...

**Comment by cruzaderplyr** [comment]
this is my config....individually works....toghether...not...

climate: 
- platform: ekon-local
  name: living
  udp_server_port: 6343
  udp_server_addr: 192.168.50.6
  device_addr: 192.168.50.58
  forward_addr: 3.137.73.173
  forward_port: 9533
  
climate: 
- platform: ekon-local
  name: habitacion
  udp_server_port: 6344
  udp_server_addr: 192.168.50.6
  device_addr: 192.168.50.59
  forward_addr: 3.137.73.173
  forward_port: 9533

**Comment by cruzaderplyr** [comment]
i review my config...and after a few tests....this works...

climate: 
- platform: ekon-local
  name: living
  udp_server_port: 6343
  udp_server_addr: 192.168.50.6
  device_addr: 192.168.50.58
  forward_addr: 3.137.73.173
  forward_port: 9533

- platform: ekon-local
  name: habitacion
  udp_server_port: 6344
  udp_server_addr: 192.168.50.6
  device_addr: 192.168.50.59
  forward_addr: 3.137.73.173
  forward_port: 9533
  
  
  you have to use different ports for each AC...and i have a "climate" for each one...
  
  the last error i have is... i still want to use the app....and the forward address is configurated with the port...but it doesnt work at all...

**Comment by hllhll** [comment]
Hi,
Grate idea with the two ports, [as stated ( in the wrong place :/ )](https://github.com/hllhll/HomeAssistant-ekon-local#features) the code does not support multiple ACs at the moment.
You basically setup the integration twice with different UDP listeners, it's awesome to hear that it works :)
For the forwarding issue, It looks like your port is wrong, for Airconet+ use 3.137.73.173, 6343 ([link](https://github.com/hllhll/HomeAssistant-EKON-iAircon/issues/19#issuecomment-713386325)) on both ACs

**Comment by cruzaderplyr** [comment]
3.137.73.173, 6343 this works!! and it works like a charm....its good to know that i can help to your awesome work with this. thanks for everything...and again...sorry for my bad english....
