### ISSUE TITLE
[Feature Request] Last Temperature/Fan speed state

### ISSUE THREAD

**Issue by yuvalmesika** [hllhll/HomeAssistant-ekon-local#21]
Hi,
Currently, each time I set the AC to off, the target temperature and the fan speed is back to default (25, and low).

I wish it could save the last target temperate and fan from the last time the AC was On.
Or add an option to set the default target temperature and fan mode (I think currently it's configured in pyekonlib in AirconStateData constructor).

**Comment by hllhll** [comment]
That begs the question, how do you turn the HVAC on?
I've created a service turn_on that _shoud_ do that , Not sure if I tried it tough.
Note that setting `mode` through Lovelace does not issue turn_on. rather sets mode to cool

**Comment by yuvalmesika** [comment]
You are right,
When turning on the HVAC from the climate.turn_on service it does preserve the last state.
I have a dashboard panel that each mode has a button,
So pushing the cold button set the mode to cold,
I guess this is why the temperature and fan takes the default configuration.

Anyway to achieve the same behavior when setting the mode?

**Comment by hllhll** [comment]
.. I Don't think so,
You could probably script something through ha, cant you?
Making him remember last temp and fan, after few seconds after mode change,
restore it.

Another solution I suggest that you switch the button to just 'on' just
like the physical console

**Comment by yuvalmesika** [comment]
Switched the button to call the turn on service. 
Thanks @hllhll
