### ISSUE TITLE
AC can't turn on in heating mode

### ISSUE THREAD

**Issue by leranp** [hllhll/HomeAssistant-ekon-local#23]
Hi,
We are in the winter now :-) and this is the first time that i need to turn on my AC on heating mode, but it look like there's a problem with turning the AC in this mode, turning on in cool mode is working great.
Tried to debug in the HA but the logs look that same with turning in Cool and heat mode.
Beside the heating mode everything working great.

**Comment by hllhll** [comment]
By turning on in heating mode, you mean clicking the "heat" mode button?
<img width="210" alt="image" src="https://user-images.githubusercontent.com/2906606/146747730-63b46ed0-9caa-49c9-b9a4-e84f47c2ccff.png">
Or switching when it's running, or both?

**Comment by leranp** [comment]
> By turning on in heating mode, you mean clicking the "heat" mode button?
> <img width="210" alt="image" src="https://user-images.githubusercontent.com/2906606/146747730-63b46ed0-9caa-49c9-b9a4-e84f47c2ccff.png">
> Or switching when it's running, or both?

Yes, or trying via google assistant

**Comment by hllhll** [comment]
Can you please describe the specific scenario?
From GA there might be issues. I just tried from ha from off to heat and it turned on

**Comment by leranp** [comment]
> Can you please describe the specific scenario?
> From GA there might be issues. I just tried from ha from off to heat and it turned on

Only tried to switch from OFF to Heat mode in HA , the AC component in Lovelace turning on in heat mode ( the AC doesn't starting) and after couple of seconds the AC component show that the AC is OFF

**Comment by leranp** [comment]
Turning the AC to cool mode and then to heat doesn't work, it look like there's something worng with the heat mode
HA version 2021.12
Doesn't remember if there was a version that worked in the past

**Comment by leranp** [comment]
It now working again, don't know what happened

**Comment by hllhll** [comment]
Please try to see if this is might be related to ha restarts, if it this, this might be some logic issue on my side (pure guess)
