### ISSUE TITLE
Junior question - what is my AC ip?

### ISSUE THREAD

**Issue by adizag** [hllhll/HomeAssistant-ekon-local#26]
How can I find it? 
tried to scan my network IP but couldn't identify the right IP of the AC...

TNX!

**Comment by CYMHILLEL** [comment]
You can either:
1. scan you're local network for any devices and eliminate, also the port on the device is 80.
2. Add the device to the network with a different APP. Such as ESPTouch (https://play.google.com/store/apps/details?id=com.khoazero123.iot_esptouch_demo&pli=1) it reports the IP of the device after adding it, I believe.
3. Try to take a look at you're router DHCP sessions or detected devices/etc

**Comment by hllhll** [comment]
You can either:
1. scan you're local network for any devices and eliminate, also the port on the device is 80.
2. Add the device to the network with a different APP. Such as ESPTouch (https://play.google.com/store/apps/details?id=com.khoazero123.iot_esptouch_demo&pli=1) it reports the IP of the device after adding it, I believe.
3. Try to take a look at you're router DHCP sessions or detected devices/etc
