### ISSUE TITLE
warnings in logs , regarding deprecated constants

### ISSUE THREAD

**Issue by orentiman** [hllhll/HomeAssistant-ekon-local#28]
hi
after upgrading ha core - 2024.4.0, i noticed in the logs some warning messages about deprecated constants .
i will be glad if it can be fixed before 2025.1 version.

as the following:

HVAC_MODE_DRY was used from ekon-local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please report it to the author of the 'ekon-local' custom integration

HVAC_MODE_FAN_ONLY was used from ekon-local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'ekon-local' custom integration

HVAC_MODE_HEAT was used from ekon-local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'ekon-local' custom integration

SUPPORT_FAN_MODE was used from ekon-local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'ekon-local' custom integration

SUPPORT_TARGET_TEMPERATURE was used from ekon-local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'ekon-local' custom integration

TEMP_CELSIUS was used from ekon-local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'ekon-local' custom integration

regards
oren

**Comment by hllhll** [comment]
Fixed with PR #29
