### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by liorm0505** [hllhll/HomeAssistant-ekon-local#7]
I am running HASSIO on an Intel NUC. 
After copying the configuration example i am getting the following error:

![image](https://user-images.githubusercontent.com/36536657/99871635-dae65c80-2be4-11eb-96bf-aa14aafce7b7.png)

HA log when trying to restart with this configuration:

`Platform error climate.ekon-local - No module named 'pyekonlib'`

**Comment by hllhll** [comment]
Hi,
Im not sure what is the procedure on every platform. On docker container install, manifest.json tells HA to download the package, 
Otherwise you would have to manually install it
https://github.com/hllhll/pyekonlib

**Comment by liorm0505** [comment]
Hi, 

So doing a  single reset of HA w/o editing the configuraiton seems to solve the problem.
Afterwareds i did the edit without any problem.

Seems like HA need to fech the library before enabling the addon in the configuration file.

Addon is working now. 

You can close the issue. 

Thanks.
